### ISSUE TITLE
Wrong expiration date property

### ISSUE THREAD

**Issue by josuemma** [auth0-blog/vuejs2-authentication-tutorial#5]
Great Tutorial, Just a quick note:

I think in the function getTokenExpirationDate the property used to get the expiration date should be token.token_expiration_date

function getTokenExpirationDate (encodedToken) {
  const token = decode(encodedToken)
  if (!token.token_expiration_date) { return null }

  const date = new Date(0)
  date.setUTCSeconds(token.token_expiration_date)

  return date
}

Cheers

**Comment by unicodeveloper** [comment]
Hello @josuemma It is not wrong.

It is actually `token.exp`. Try to log the value of token in your console to see all its properties. `exp` is the property that denotes the token expiration date.

![debugger](https://user-images.githubusercontent.com/2946769/29483897-69336842-84aa-11e7-9009-9dedfb6a0fa7.png)

Date in UTC is the is when the `token.exp` value has been converted to UTC.
